name: Build project

on: [push]

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Compile the Project
        run: mvn -B compile
      - name: Test the Project
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
           verbose: true