name: Perform coverity scan
 
permissions:
  contents: read

on: 
  push:
     branches:
         - coverity_scan

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: vapier/coverity-scan-action@v1
      with:
        build_language: 'java'
        command: 'mvn -DskipTests=true compile'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
